### ISSUE TITLE
[Request] Compilation and usage instructions

### ISSUE THREAD

**Issue by waltergallegog** [fukunagatsu/CentroidLinAliFold#1]
Dear developer,
I'm interested in using your tools for RNA consensus folding (this repo and [LinAliFold](https://github.com/fukunagatsu/LinAliFold))
If possible could you please add some compilation and usage instruction in the README files. It would be very helpful.
Thanks in advance,
Walter.

**Comment by fukunagatsu** [comment]
Dear Walter,

Thanks for your interest in our software!
According to the reviewer's suggestion, we will merge LinAliFold and CentroidLinAliFold repositories in a few days. At that time, we will also update the README files.

Best,
Tsukasa Fukunaga

**Comment by waltergallegog** [comment]
Dear Tsukasa Fukunaga,
Thanks for your quick reply. Could you please update this thread after the merge is completed?
Best,
Walter.

**Comment by fukunagatsu** [comment]
Dear Walter,

We mergerd folders and updated README.
Please run the make command in the folder with Makefile, and then two tools are generated  in the bin folder.

Best,
Tsukasa Fukunaga

**Comment by waltergallegog** [comment]
Dear Tsukasa Fukunaga,
Thanks for the update.
BR,
Walter.
